### ISSUE TITLE
UI: date selection circle isn't centered around 2-digit dates

### ISSUE THREAD

**Issue by pakx** [CreaturesInUnitards/mithril-datepicker#8]
pls see item labeled "offset" in attached screenshot

![datepicker-header-offset](https://user-images.githubusercontent.com/19353048/28226079-ce1bef00-68a2-11e7-8a05-b6575493e4db.png)

**Comment by CreaturesInUnitards** [comment]
Fixed, I think. I couldn't repro, but the larger size of the new iteration visually absorb any 1- and 2-pixel flaws like the one shown here. Could you please confirm?

**Comment by pakx** [comment]
Looks OK on the larger size ... but is this larger size fixed? I didn't see options for setting dimensions. If so it seems unusable in many scenarios, don't you think?

**Comment by CreaturesInUnitards** [comment]
I settled on this default size — 308px — because it's mobile-ready, with Apple-approved hit target sizes :).

It's "fixed", sort of, but I'm not going to expose an API for resizing. The sass file is pretty straightforward, with variables up top that make it pretty easy to customize without digging too deeply into the css implementation details. One of the things that drives me up the wall with the Bootstraps and Foundations of the world is how much overhead they carry just to offer API-driven configuration. IMHO ```lessCode ~ moreTransparentCode ~ moreEasilyCustomizedCode```.

That said, there are some hard-coded values in there that need to be cleaned up, for sure. Question: was this screenshot taken in Firefox?

**Comment by pakx** [comment]
Yes, FF

**Comment by CreaturesInUnitards** [comment]
gave up, ditched circles. FF just can't play nice with sub-pixel math, it would appear.
